- name: Teams
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install Teams (macOS)
      homebrew_cask:
        name: microsoft-teams
      when: is_mac
