- name: Azure (az)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:

    # macOS

    - name: Install Azure CLI (macOS)
      homebrew:
        name: azure-cli
      when: is_mac
