- name: Azure (Storage Explorer)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install Storage Explorer (macOS)
      homebrew_cask:
        name: microsoft-azure-storage-explorer
      when: is_mac
