- name: Core OS customization 
  hosts: 127.0.0.1
  connection: local

  vars:
    # macOS

    - name: Install Fonts (macOS)
      homebrew_tap:
        name: homebrew/cask-fonts
      homebrew_cask:
        name: font-hack-nerd-font
