- name: Core OS customization 
  hosts: 127.0.0.1
  connection: local

  tasks:
    # macOS

    - name: Add tap
      homebrew_tap:
        name: homebrew/cask-fonts

    - name: Install Fonts
      homebrew_cask:
        name: font-hack-nerd-font
