- name: VLC
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install VLC (macOS)
      homebrew_cask:
        name: vlc
      when: is_mac
