- name: Neovim
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Create tmp directory
      file:
        path: ~/tmp/
        state: directory

    - name: Download nvim/nightly
      get_url:
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
        dest: ~/tmp/
        mode: 0400

    - name: Extract nvim/nightly (macOS)
      shell: 
        cmd: tar xzvf ~/tmp/nvim-macos.tar.gz

    - name: Install nvim/nightly (macOS)
      shell: 
        chdir: nvim-osx64/
        cmd: mv bin/nvim /usr/local/bin/; mv lib/nvim/ /usr/local/lib/; mv /libs/* /usr/local/lib/; mv share/* /usr/local/share/
