- name: Neovim
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Create tmp directory
      file:
        path: ~/tmp/
        state: directory
      shell: /bin/rm -rf ~/tmp/*

    - name: Download nvim/nightly
      get_url:
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
        dest: ~/tmp/
        mode: 0400

    - name: Extract nvim/nightly (macOS)
      unarchive:
        src: "~/tmp/nvim-macos.tar.gz"
        dest: "~/tmp"
        creates: "~/tmp/nvim-osx64/"

    - name: Install nvim/nightly (macOS)
      shell: 
        chdir: ~/tmp/nvim-osx64/
        cmd: mv -n bin/nvim /usr/local/bin/; mv -n lib/nvim/ /usr/local/lib/; mv -n /libs/* /usr/local/lib/; mv -n share/* /usr/local/share/
