- name: Zoom
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:

    # macOS

    - name: Install Zoom (macOS)
      homebrew_cask:
        name: zoomus
      when: is_mac
