- name: Docker
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

    # macOS

    - name: Install Docker CLI components (macOS)
      homebrew:
        name: docker-compose
      when: is_mac

    - name: Install Docker engine (macOS)
      homebrew_cask:
        name: docker
      when: is_mac
