- name: Virtualization
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install VirtualBox (macOS)
      homebrew_cask:
        name: virtualbox
      when: is_mac
    - name: Install Vagrant (macOS)
      homebrew_cask:
        name: vagrant
      when: is_mac
