- name: VS Code
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install VS Code (macOS)
      homebrew_cask:
        name: visual-studio-code
      when: is_mac
