- name: .NET
  hosts: 127.0.0.1
  connection: local

  vars:
    dotnet_versions:
      - "2.1"
      - "3.1"
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install .NET SDK installer
      get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: ~/bin/dotnet-install
        mode: 0755
      when: is_mac

    - name: Install .NET SDK (macOS)
      shell: ~/bin/dotnet-install -c {{ item }}
      register: dotnet_sdk_installed_mac
      loop: "{{ dotnet_versions }}"
      args:
        creates: ~/.dotnet/sdk/{{ item }}.*/.version
      when: is_mac

    - name: Create shortcut to dotnet
      file:
        path: ~/bin/dotnet
        src: ~/.dotnet/dotnet
        state: link
      when: is_mac

    - name: Perform first-run experience (macOS)
      command: ~/bin/dotnet new
      when: dotnet_sdk_installed_mac.changed
