- name: kubectl
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install bash completion support
      homebrew:
        name: bash-completion
      register: bash_completion
      when: is_mac

    - name: Add bash completion support to shell
      lineinfile:
        path: ~/.bashrc
        line: source $(brew --prefix)/etc/bash_completion
      when: bash_completion.changed

    - name: Install kubectl (macOS)
      homebrew:
        name: kubectl
      when: is_mac

    # Common

    - name: Enable bash completion for kubectl
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Enable kubectl auto-complete"
        block: |
          eval "$(kubectl completion zsh)"
