- name: Google Chrome
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install Google Chrome (macOS)
      homebrew_cask:
        name: google-chrome
      when: is_mac
