- name: GitHub (gh)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install gh CLI (macOS)
      homebrew:
        name: gh
      when: is_mac
