- name: GitHub (hub)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install hub CLI (macOS)
      homebrew:
        name: hub
      when: is_mac
