- name: NodeJS (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Test for installed NodeJS LTS
      shell: zsh -ic "nvm ls lts" >/dev/null
      register: nvm_ls
      ignore_errors: yes

    - name: Install NodeJS LTS
      command: zsh -ic "nvm install --lts"
      when: nvm_ls.failed

    - name: Use NodeJS LTS by default
      command: zsh -ic "nvm use --lts"
      when: nvm_ls.failed
