- name: NodeJS (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Test for installed NodeJS LTS
      shell: 
        cmd: nvm ls lts/* > /dev/null
      register: nvm_ls
      ignore_errors: yes

    - name: Install NodeJS LTS
        cmd: nvm install lts/*
      when: nvm_ls.failed

    - name: Use NodeJS LTS by default
      shell:
        cmd: nvm use --lts
      when: nvm_ls.failed
