- name: NodeJS (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Test for installed NodeJS LTS
      shell: nvm ls lts > /dev/null
      args:
          executable: /bin/zsh
      register: nvm_ls
      ignore_errors: yes

    - name: Install NodeJS LTS
      shell: nvm install --lts
      args:
          executable: /bin/zsh
      when: nvm_ls.failed

    - name: Use NodeJS LTS by default
      shell: nvm use --lts
      args:
          executable: /bin/zsh
      when: nvm_ls.failed
