- name: Spotify
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install Spotify (macOS)
      homebrew_cask:
        name: spotify
      when: is_mac
