- name: Mono
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # macOS

    - name: Install Mono (macOS)
      homebrew:
        name: mono
      when: is_mac
