- name: iTerm2
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

    # macOS

    - name: Install iTerm2 (macOS)
      homebrew_cask:
        name: iterm2
      when: is_mac
